sy on
set ai nu ru cul mouse=a bg=dark
set cin et ts=4 sw=4 sts=4
im jk <esc> | im kj <esc>
im ( ()<esc>i
im [ []<esc>i
im {<cr> {<cr>}<esc>ko
nnoremap run :w<bar>!g++ -std=c++14 -DLOCAL -Wfatal-errors -o test "%" && echo "done." && time ./test<CR>
